---
{{- $ns := .observed.composite.resource.metadata.name | replace "." "-" }}

apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: namespace
    crossplane.io/external-name: {{ $ns }}
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ $ns }}
        labels:
          konflux-ci.dev/namespace-type: eaas
  providerConfigRef:
    name: eaas-kubernetes-provider-config

---
apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
kind: Context
data:
  namespace: {{ $ns }}
